ServerInfo:
  name: "Ginn"
  desc: "This is open soucer ginn"
  version: "v1.1.1"
  host: "127.0.0.1"
  port: ":9090"
  mode: "debug"
  startTime: "2020-11-05"
  machineId: 1
  secretKey: "HELLOGinn^^^^^!!!@@@888($%)++__@#!$%^OPENkk"

MysqlInfo:
  dbName: "ginn"
  userName: "root"
  passWord: "123456"
  host: "127.0.0.1"
  port: "3306"
  charset: "utf8mb4"

RedisInfo:
  dbName: 0
  userName: ""
  passWorld: ""
  host: "127.0.0.1"
  port: "6379"
  poolSize: 10

#这里需要填自己七牛云信息哈
QiNiuInfo:
  accessKey: ""
  secretKey: ""
  imageUrl: "http://qjb6cx7vp.hn-bkt.clouddn.com/"
  bucket: "ginn"

Auth:
  jwtExpire: 8760
  secretKey: "ginn12345678!EQWt@#$%^&*#!@#%ginn"
  coxFlag: "UserId"

Email:
  addr: "smtp.qq.com:25"
  form: "ginn <1209371783@qq.com>"
  username: "1209371783@qq.com"
  password: "123456"
  host: "smtp.qq.com"